docker build progress

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,6 +38,16 @@ jobs:
 
     - name: Build with Gradle Wrapper
       run: ./gradlew build
+    
+    - name: Verify JAR file exists
+      run: |
+          if [ ! -f build/libs/*.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
+
+    - name: List directory contents
+      run: ls -la
 
     # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
     # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
@@ -94,7 +104,7 @@ jobs:
       uses: docker/build-push-action@v2
       with:
         context: .
-        file: ../Dockerfile
+        file: ./Dockerfile
         push: true
         tags: |
           ${{ secrets.DOCKER_USERNAME }}/java-ci-cd-app:latest
