Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -41,6 +41,14 @@ jobs:
 
     - name: Build with Gradle Wrapper
       run: ./gradlew build
+    
+    - uses: mr-smithers-excellent/docker-build-push@v4
+      name: Build and push docker image
+      with:
+        image: sherifadavuruku/java-ci-cd-app
+        registry: docker.io
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }} 
 
     # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
     # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
@@ -74,42 +82,33 @@ jobs:
     # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
     
 
-  publish:
-    needs: build #this indicate that this job depends on the build jobs
-    runs-on: ${{matrix.os}} # it should run on 3 os platform
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-    permissions:
-      contents: read
+  # publish:
+  #   needs: build #this indicate that this job depends on the build jobs
+  #   runs-on: ${{matrix.os}} # it should run on 3 os platform
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-latest]
+  #   permissions:
+  #     contents: read
 
-    steps:
-    - name: Verify JAR file exists
-      run: |
-          if [ ! -f build/libs/*.jar ]; then
-            echo "JAR file not found!"
-            exit 1
-          fi
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #     name: Check out code
 
-    - name: List directory contents
-      run: ls -la
+  #   - name: Verify JAR file exists
+  #     run: |
+  #         if [ ! -f build/libs/*.jar ]; then
+  #           echo "JAR file not found!"
+  #           exit 1
+  #         fi
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+  #   - name: List directory contents
+  #     run: ls -la
 
-    - name: Login to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
-
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        file: ./Dockerfile
-        push: true
-        tags: |
-          ${{ secrets.DOCKER_USERNAME }}/java-ci-cd-app:latest
-          ${{ secrets.DOCKER_USERNAME }}/java-ci-cd-app:${{ github.sha }}
-          ${{ secrets.DOCKER_USERNAME }}/java-ci-cd-app:${{ github.ref_name }}-${{ github.sha }}
+  #   - uses: mr-smithers-excellent/docker-build-push@v4
+  #     name: Build and push docker image
+  #     with:
+  #       image: sherifadavuruku/java-ci-cd-app
+  #       registry: docker.io
+  #       username: ${{ secrets.DOCKER_USERNAME }}
+  #       password: ${{ secrets.DOCKER_PASSWORD }} 
